AWSTemplateFormatVersion: '2010-09-09'
Description: Despliegue de infraestructura (S3 y EC2).

Parameters:
  KeyName:
    Description: Nombre del par de llaves para SSH
    Type: AWS::EC2::KeyPair::KeyName
    Default: vockey

Resources:
  # 1. Bucket S3 para almacenamiento de datos
  BucketDevops:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "bucket-devops-${AWS::AccountId}" # Nombre único global
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # 2. Grupo de Seguridad para la EC2
  ServidorSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      #Permite acceso por SSH utilizando protocolo IP TCP. Comunicación por puerto 22 desde cualquier IP.
      GroupDescription: Permitir SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  # 3. Instancia EC2
  ServidorApp:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}' # Amazon Linux 2023 en us-east-1
      KeyName: !Ref KeyName
      #La instancia está ligada al grupo de seguridad anterior
      SecurityGroupIds:
        - !Ref ServidorSecurityGroup
      # Uso del rol de instancias predefinido en AWS Academy
      IamInstanceProfile: "LabInstanceProfile"
      Tags:
        - Key: Name
          Value: Servidor-Financiero-IaC
        - Key: Proyecto
          Value: SolucionesFuturo

Outputs:
  BucketName:
    Description: Nombre del bucket creado
    Value: !Ref BucketDevops
  InstancePublicIP:
    Description: IP pública de la instancia
    Value: !GetAtt ServidorApp.PublicIp